import type {
  AdminUser,
  AuditEvent,
  FeedbackItem,
  KnowledgeDocument,
  UsageStats,
} from './types'

export const adminUsers: readonly AdminUser[] = Object.freeze([
  {
    id: 'user-001',
    name: '王小明',
    email: 'xiaoming.wang@citygpt.example',
    department: '農業處',
    role: 'knowledge_admin',
    status: 'active',
    lastLogin: '2026-07-06T08:42:00+08:00',
  },
  {
    id: 'user-002',
    name: '林怡君',
    email: 'yijun.lin@citygpt.example',
    department: '計畫處',
    role: 'system_admin',
    status: 'active',
    lastLogin: '2026-07-06T09:05:00+08:00',
  },
  {
    id: 'user-003',
    name: '陳志豪',
    email: 'zhihao.chen@citygpt.example',
    department: '政風處',
    role: 'auditor',
    status: 'active',
    lastLogin: '2026-07-05T16:18:00+08:00',
  },
  {
    id: 'user-004',
    name: '張雅雯',
    email: 'yawen.zhang@citygpt.example',
    department: '民政處',
    role: 'analyst',
    status: 'invited',
    lastLogin: null,
  },
  {
    id: 'user-005',
    name: '李承翰',
    email: 'chenghan.li@citygpt.example',
    department: '社會處',
    role: 'knowledge_admin',
    status: 'suspended',
    lastLogin: '2026-06-19T11:27:00+08:00',
  },
  {
    id: 'user-006',
    name: '黃品蓁',
    email: 'pinzhen.huang@citygpt.example',
    department: '教育處',
    role: 'analyst',
    status: 'active',
    lastLogin: '2026-07-04T14:03:00+08:00',
  },
  {
    id: 'user-007',
    name: '許家維',
    email: 'jiawei.xu@citygpt.example',
    department: '資訊中心',
    role: 'system_admin',
    status: 'invited',
    lastLogin: null,
  },
])

export const knowledgeDocuments: readonly KnowledgeDocument[] = Object.freeze([
  {
    id: 'doc-001',
    name: '農業政策手冊',
    knowledgeBase: '農業服務知識庫',
    category: '政策與補助',
    version: 'v2.1-draft',
    access: 'department',
    published: false,
    indexStatus: 'pending',
    updatedAt: '2026-07-05T13:20:00+08:00',
    updatedBy: '王小明',
  },
  {
    id: 'doc-002',
    name: '縣政 FAQ',
    knowledgeBase: '縣民服務知識庫',
    category: '常見問答',
    version: 'v4.3',
    access: 'public',
    published: true,
    indexStatus: 'failed',
    updatedAt: '2026-07-06T07:35:00+08:00',
    updatedBy: '林怡君',
  },
  {
    id: 'doc-003',
    name: '育兒津貼申請指南',
    knowledgeBase: '社會福利知識庫',
    category: '補助申請',
    version: 'v3.0',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-07-03T10:05:00+08:00',
    updatedBy: '李承翰',
  },
  {
    id: 'doc-004',
    name: '校園防災作業要點',
    knowledgeBase: '教育行政知識庫',
    category: '校園安全',
    version: 'v1.8',
    access: 'department',
    published: true,
    indexStatus: 'indexing',
    updatedAt: '2026-07-05T17:10:00+08:00',
    updatedBy: '黃品蓁',
  },
  {
    id: 'doc-005',
    name: '採購稽核檢核表',
    knowledgeBase: '內部治理知識庫',
    category: '稽核',
    version: 'v2.4',
    access: 'restricted',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-06-28T15:42:00+08:00',
    updatedBy: '陳志豪',
  },
  {
    id: 'doc-006',
    name: '戶籍異動服務說明',
    knowledgeBase: '縣民服務知識庫',
    category: '戶政服務',
    version: 'v5.2',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-07-01T09:12:00+08:00',
    updatedBy: '張雅雯',
  },
  {
    id: 'doc-007',
    name: '災害應變通報流程',
    knowledgeBase: '災害應變知識庫',
    category: '標準作業程序',
    version: 'v1.6',
    access: 'restricted',
    published: false,
    indexStatus: 'pending',
    updatedAt: '2026-07-04T18:30:00+08:00',
    updatedBy: '許家維',
  },
  {
    id: 'doc-008',
    name: '長者福利資源總覽',
    knowledgeBase: '社會福利知識庫',
    category: '福利服務',
    version: 'v2.7',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-06-30T11:45:00+08:00',
    updatedBy: '李承翰',
  },
])

const auditEventSamples: AuditEvent[] = [
  {
    id: 'audit-001',
    timestamp: '2026-07-06T09:08:12+08:00',
    actor: '林怡君',
    ip: '192.0.2.10',
    module: '使用者管理',
    action: '邀請管理者',
    result: 'success',
    resource: 'user-007',
    traceId: 'trc-20260706-0001',
    before: null,
    after: { role: 'system_admin', status: 'invited' },
    permissionDecision: 'allowed: users.manage',
  },
  {
    id: 'audit-002',
    timestamp: '2026-07-06T08:51:40+08:00',
    actor: '王小明',
    ip: '192.0.2.24',
    module: '知識庫管理',
    action: '更新文件版本',
    result: 'success',
    resource: 'doc-001',
    traceId: 'trc-20260706-0002',
    before: { version: 'v2.0-draft' },
    after: { version: 'v2.1-draft' },
    permissionDecision: 'allowed: knowledge.manage',
  },
  {
    id: 'audit-003',
    timestamp: '2026-07-06T08:02:15+08:00',
    actor: '張雅雯',
    ip: '198.51.100.14',
    module: '知識庫管理',
    action: '發布文件',
    result: 'failed',
    resource: 'doc-006',
    traceId: 'trc-20260706-0003',
    before: { published: true },
    after: { published: true },
    permissionDecision: 'denied: knowledge.manage',
  },
  {
    id: 'audit-004',
    timestamp: '2026-07-05T17:14:33+08:00',
    actor: '黃品蓁',
    ip: '198.51.100.27',
    module: '統計分析',
    action: '匯出部門報表',
    result: 'success',
    resource: 'stats-30d-education',
    traceId: 'trc-20260705-0004',
    before: null,
    after: { format: 'csv', rangeDays: 30 },
    permissionDecision: 'allowed: stats.view',
  },
  {
    id: 'audit-005',
    timestamp: '2026-07-05T16:22:08+08:00',
    actor: '陳志豪',
    ip: '203.0.113.8',
    module: '稽核日誌',
    action: '查詢失敗事件',
    result: 'success',
    resource: 'audit-filter-failed',
    traceId: 'trc-20260705-0005',
    before: { filter: 'all' },
    after: { filter: 'failed' },
    permissionDecision: 'allowed: audit.view',
  },
  {
    id: 'audit-006',
    timestamp: '2026-07-05T14:36:49+08:00',
    actor: '李承翰',
    ip: '203.0.113.31',
    module: '回饋管理',
    action: '指派負責人',
    result: 'failed',
    resource: 'feedback-004',
    traceId: 'trc-20260705-0006',
    before: { assignee: null },
    after: { assignee: null },
    permissionDecision: 'denied: account suspended',
  },
  {
    id: 'audit-007',
    timestamp: '2026-07-04T18:42:21+08:00',
    actor: '許家維',
    ip: '192.0.2.45',
    module: '使用者管理',
    action: '啟用帳號',
    result: 'failed',
    resource: 'user-005',
    traceId: 'trc-20260704-0007',
    before: { status: 'suspended' },
    after: { status: 'suspended' },
    permissionDecision: 'denied: invitation not accepted',
  },
  {
    id: 'audit-008',
    timestamp: '2026-07-04T15:09:57+08:00',
    actor: '系統索引服務',
    ip: '192.0.2.200',
    module: '知識庫管理',
    action: '重建文件索引',
    result: 'failed',
    resource: 'doc-002',
    traceId: 'trc-20260704-0008',
    before: { indexStatus: 'indexing' },
    after: { indexStatus: 'failed', errorCode: 'CONTENT_PARSE_ERROR' },
    permissionDecision: 'allowed: service principal knowledge.manage',
  },
]

export const auditEvents: readonly AuditEvent[] = Object.freeze(
  auditEventSamples.map((event) => Object.freeze(event)),
)

export const usageStats: readonly UsageStats[] = Object.freeze([
  {
    rangeDays: 7,
    kpis: {
      totalQueries: 12480,
      activeUsers: 1842,
      averageResponseMs: 1280,
      satisfactionRate: 0.91,
    },
    trends: [
      { date: '2026-07-04', queries: 1710, activeUsers: 298 },
      { date: '2026-07-05', queries: 1665, activeUsers: 276 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '縣民服務知識庫', queries: 4150, satisfactionRate: 0.93 },
      { name: '社會福利知識庫', queries: 2880, satisfactionRate: 0.9 },
      { name: '農業服務知識庫', queries: 2140, satisfactionRate: 0.89 },
    ],
    departmentRanking: [
      { department: '民政處', queries: 2380, activeUsers: 310 },
      { department: '社會處', queries: 2015, activeUsers: 274 },
      { department: '農業處', queries: 1840, activeUsers: 236 },
    ],
    unansweredRate: 0.043,
    errorSummaries: [
      { code: 'NO_MATCH', count: 312, description: '找不到足夠相關的知識片段' },
      { code: 'INDEX_UNAVAILABLE', count: 47, description: '文件索引暫時不可用' },
    ],
  },
  {
    rangeDays: 30,
    kpis: {
      totalQueries: 51860,
      activeUsers: 5340,
      averageResponseMs: 1345,
      satisfactionRate: 0.9,
    },
    trends: [
      { date: '2026-06-07', queries: 1490, activeUsers: 268 },
      { date: '2026-06-21', queries: 1760, activeUsers: 301 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '縣民服務知識庫', queries: 16820, satisfactionRate: 0.92 },
      { name: '社會福利知識庫', queries: 12310, satisfactionRate: 0.9 },
      { name: '教育行政知識庫', queries: 8270, satisfactionRate: 0.88 },
    ],
    departmentRanking: [
      { department: '民政處', queries: 9840, activeUsers: 872 },
      { department: '社會處', queries: 8650, activeUsers: 741 },
      { department: '教育處', queries: 7290, activeUsers: 688 },
    ],
    unansweredRate: 0.049,
    errorSummaries: [
      { code: 'NO_MATCH', count: 1422, description: '找不到足夠相關的知識片段' },
      { code: 'TIMEOUT', count: 118, description: '回應產生超過服務時間上限' },
    ],
  },
  {
    rangeDays: 90,
    kpis: {
      totalQueries: 142730,
      activeUsers: 9815,
      averageResponseMs: 1410,
      satisfactionRate: 0.885,
    },
    trends: [
      { date: '2026-04-08', queries: 1280, activeUsers: 231 },
      { date: '2026-05-23', queries: 1585, activeUsers: 279 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '縣民服務知識庫', queries: 45110, satisfactionRate: 0.91 },
      { name: '社會福利知識庫', queries: 32180, satisfactionRate: 0.89 },
      { name: '農業服務知識庫', queries: 22420, satisfactionRate: 0.87 },
    ],
    departmentRanking: [
      { department: '民政處', queries: 26340, activeUsers: 1570 },
      { department: '社會處', queries: 23870, activeUsers: 1432 },
      { department: '農業處', queries: 19740, activeUsers: 1215 },
    ],
    unansweredRate: 0.054,
    errorSummaries: [
      { code: 'NO_MATCH', count: 4280, description: '找不到足夠相關的知識片段' },
      { code: 'SOURCE_STALE', count: 306, description: '引用來源已超過更新週期' },
    ],
  },
])

export const feedbackItems: readonly FeedbackItem[] = Object.freeze([
  {
    id: 'feedback-001',
    sentiment: 'negative',
    question: '今年小型農機補助的申請截止日是什麼時候？',
    answer: '目前知識庫沒有找到可確認的截止日期，建議洽詢農業處。',
    department: '農業處',
    knowledgeBase: '農業服務知識庫',
    tags: ['補助', '待補資料'],
    status: 'pending',
    createdAt: '2026-07-06T08:28:00+08:00',
    assignee: null,
    note: '需要補上 2026 年度公告與截止日期。',
    citations: [
      {
        documentId: 'doc-001',
        documentName: '農業政策手冊',
        excerpt: '農機補助依年度公告辦理。',
      },
    ],
    context: {
      traceId: 'feedback-trc-001',
      conversationId: 'conversation-001',
      channel: '縣民入口網站',
    },
  },
  {
    id: 'feedback-002',
    sentiment: 'positive',
    question: '新生兒育兒津貼要準備哪些文件？',
    answer: '需準備申請書、申請人身分證明與指定帳戶資料。',
    department: '社會處',
    knowledgeBase: '社會福利知識庫',
    tags: ['育兒津貼', '申請文件'],
    status: 'completed',
    createdAt: '2026-07-05T19:45:00+08:00',
    assignee: '社福知識維護小組',
    note: '使用者確認回答清楚。',
    citations: [
      {
        documentId: 'doc-003',
        documentName: '育兒津貼申請指南',
        excerpt: '申請應檢附身分證明及金融帳戶資料。',
      },
    ],
    context: {
      traceId: 'feedback-trc-002',
      conversationId: 'conversation-002',
      channel: 'LINE 服務帳號',
    },
  },
  {
    id: 'feedback-003',
    sentiment: 'negative',
    question: '遷入戶籍可以完全線上辦理嗎？',
    answer: '可以在線上完成所有遷入程序。',
    department: '民政處',
    knowledgeBase: '縣民服務知識庫',
    tags: ['戶政', '內容勘誤'],
    status: 'in_progress',
    createdAt: '2026-07-05T14:12:00+08:00',
    assignee: '戶政內容小組',
    note: '部分情況仍須臨櫃核驗，正在修正回答規則。',
    citations: [
      {
        documentId: 'doc-006',
        documentName: '戶籍異動服務說明',
        excerpt: '線上預約後，依個案通知完成身分核驗。',
      },
    ],
    context: {
      traceId: 'feedback-trc-003',
      conversationId: 'conversation-003',
      channel: '縣民入口網站',
    },
  },
  {
    id: 'feedback-004',
    sentiment: 'positive',
    question: '校園防災演練多久需要辦理一次？',
    answer: '各校每學期至少辦理一次防災演練。',
    department: '教育處',
    knowledgeBase: '教育行政知識庫',
    tags: ['校園安全', '防災'],
    status: 'completed',
    createdAt: '2026-07-04T16:22:00+08:00',
    assignee: '教育知識維護小組',
    note: '引用段落與回答一致。',
    citations: [
      {
        documentId: 'doc-004',
        documentName: '校園防災作業要點',
        excerpt: '防災演練應於每學期至少實施一次。',
      },
    ],
    context: {
      traceId: 'feedback-trc-004',
      conversationId: 'conversation-004',
      channel: '內部服務台',
    },
  },
  {
    id: 'feedback-005',
    sentiment: 'negative',
    question: '哪裡可以查詢最新的颱風停班停課資訊？',
    answer: '請參考災害應變知識庫內的通報流程。',
    department: '計畫處',
    knowledgeBase: '災害應變知識庫',
    tags: ['防災', '資訊時效'],
    status: 'ignored',
    createdAt: '2026-07-03T20:06:00+08:00',
    assignee: '平台營運小組',
    note: '問題需要即時資訊，已改由官方即時資訊卡處理。',
    citations: [
      {
        documentId: 'doc-007',
        documentName: '災害應變通報流程',
        excerpt: '應變資訊依中央及縣府正式公告更新。',
      },
    ],
    context: {
      traceId: 'feedback-trc-005',
      conversationId: 'conversation-005',
      channel: 'LINE 服務帳號',
    },
  },
  {
    id: 'feedback-006',
    sentiment: 'positive',
    question: '長者有哪些交通相關福利？',
    answer: '符合資格的長者可申請敬老愛心卡，補助依最新公告辦理。',
    department: '社會處',
    knowledgeBase: '社會福利知識庫',
    tags: ['長者福利', '交通'],
    status: 'in_progress',
    createdAt: '2026-07-02T11:38:00+08:00',
    assignee: '社福知識維護小組',
    note: '正在補充申請地點連結。',
    citations: [
      {
        documentId: 'doc-008',
        documentName: '長者福利資源總覽',
        excerpt: '敬老愛心卡提供符合資格者交通補助。',
      },
    ],
    context: {
      traceId: 'feedback-trc-006',
      conversationId: 'conversation-006',
      channel: '縣民入口網站',
    },
  },
])
