import type {
  AdminUser,
  AuditEvent,
  FeedbackItem,
  KnowledgeDocument,
  UserTrafficStats,
  UsageStats,
} from './types'

const deepFreeze = <T>(value: T): Readonly<T> => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value)
    for (const nested of Object.values(value as Record<string, unknown>)) {
      deepFreeze(nested)
    }
  }

  return value as Readonly<T>
}

export const adminUsers: readonly AdminUser[] = deepFreeze([
  {
    id: 'user-001',
    name: '王小明',
    email: 'xiaoming.wang@citygpt.example',
    department: '民政處',
    role: 'user',
    status: 'sso_active',
    lastLogin: '2026-07-06T08:42:00+08:00',
  },
  {
    id: 'user-002',
    name: '林怡君',
    email: 'yijun.lin@citygpt.example',
    department: '社會處',
    role: 'user',
    status: 'sso_active',
    lastLogin: '2026-07-06T09:05:00+08:00',
  },
  {
    id: 'user-003',
    name: '陳志豪',
    email: 'zhihao.chen@citygpt.example',
    department: '建設處',
    role: 'user',
    status: 'sso_active',
    lastLogin: '2026-07-05T16:18:00+08:00',
  },
  {
    id: 'user-004',
    name: '張雅雯',
    email: 'yawen.zhang@citygpt.example',
    department: '1999 服務中心',
    role: 'user',
    status: 'sync_error',
    lastLogin: null,
  },
  {
    id: 'user-005',
    name: '李承翰',
    email: 'chenghan.li@citygpt.example',
    department: '資訊處',
    role: 'admin',
    status: 'sso_disabled',
    lastLogin: '2026-06-19T11:27:00+08:00',
  },
  {
    id: 'user-006',
    name: '黃品蓁',
    email: 'pinzhen.huang@citygpt.example',
    department: '資訊處',
    role: 'admin',
    status: 'sso_active',
    lastLogin: '2026-07-04T14:03:00+08:00',
  },
  {
    id: 'user-007',
    name: '許家維',
    email: 'jiawei.xu@citygpt.example',
    department: '人事處',
    role: 'admin',
    status: 'sso_active',
    lastLogin: null,
  },
])

export const knowledgeDocuments: readonly KnowledgeDocument[] = deepFreeze([
  {
    id: 'doc-001',
    name: '民政戶籍補助說明',
    knowledgeBase: '民政服務知識庫',
    source: 'SharePoint / 民政處',
    category: '補助與申請',
    version: 'v2.1-draft',
    access: 'department',
    published: false,
    indexStatus: 'pending',
    syncStatus: 'completed',
    readStatus: 'completed',
    searchableStatus: 'waiting_retry',
    failureReason: '草稿尚未上架，等待納入可搜尋資料。',
    lastSyncedAt: '2026-07-05T13:35:00+08:00',
    updatedAt: '2026-07-05T13:20:00+08:00',
    updatedBy: '王小明',
  },
  {
    id: 'doc-002',
    name: '1999 服務 FAQ',
    knowledgeBase: '市政服務知識庫',
    source: '內部文件庫 / 1999',
    category: '常見問題',
    version: 'v4.3',
    access: 'public',
    published: true,
    indexStatus: 'failed',
    syncStatus: 'completed',
    readStatus: 'failed',
    searchableStatus: 'failed',
    failureReason: 'PDF 表格格式不支援，需轉為可讀文字後重新執行。',
    lastSyncedAt: '2026-07-06T07:42:00+08:00',
    updatedAt: '2026-07-06T07:35:00+08:00',
    updatedBy: '林怡君',
  },
  {
    id: 'doc-003',
    name: '社福津貼資格判斷',
    knowledgeBase: '社會福利知識庫',
    source: 'SharePoint / 社會處',
    category: '福利資格',
    version: 'v3.0',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    syncStatus: 'completed',
    readStatus: 'completed',
    searchableStatus: 'completed',
    failureReason: null,
    lastSyncedAt: '2026-07-03T10:20:00+08:00',
    updatedAt: '2026-07-03T10:05:00+08:00',
    updatedBy: '李承翰',
  },
  {
    id: 'doc-004',
    name: '建築執照流程說明',
    knowledgeBase: '建設處知識庫',
    source: 'SharePoint / 建設處',
    category: '建築管理',
    version: 'v1.8',
    access: 'department',
    published: true,
    indexStatus: 'indexing',
    syncStatus: 'processing',
    readStatus: 'completed',
    searchableStatus: 'processing',
    failureReason: '建立搜尋資料中，尚未完成向量索引。',
    lastSyncedAt: '2026-07-05T17:20:00+08:00',
    updatedAt: '2026-07-05T17:10:00+08:00',
    updatedBy: '黃品蓁',
  },
  {
    id: 'doc-005',
    name: '稽核紀錄保存規範',
    knowledgeBase: '資安稽核知識庫',
    source: '資安文件庫',
    category: '稽核',
    version: 'v2.4',
    access: 'restricted',
    published: true,
    indexStatus: 'completed',
    syncStatus: 'completed',
    readStatus: 'completed',
    searchableStatus: 'completed',
    failureReason: null,
    lastSyncedAt: '2026-06-28T15:58:00+08:00',
    updatedAt: '2026-06-28T15:42:00+08:00',
    updatedBy: '陳志豪',
  },
  {
    id: 'doc-006',
    name: '1999 話術與轉介原則',
    knowledgeBase: '市政服務知識庫',
    source: '內部文件庫 / 1999',
    category: '客服話術',
    version: 'v5.2',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    syncStatus: 'completed',
    readStatus: 'completed',
    searchableStatus: 'completed',
    failureReason: null,
    lastSyncedAt: '2026-07-01T09:30:00+08:00',
    updatedAt: '2026-07-01T09:12:00+08:00',
    updatedBy: '張雅雯',
  },
  {
    id: 'doc-007',
    name: '工務案件進度查詢',
    knowledgeBase: '工務處知識庫',
    source: 'SharePoint / 工務處',
    category: '道路與工程',
    version: 'v1.6',
    access: 'restricted',
    published: false,
    indexStatus: 'pending',
    syncStatus: 'waiting_retry',
    readStatus: 'waiting_retry',
    searchableStatus: 'waiting_retry',
    failureReason: '同步等待超過 6 小時，待 RD 確認排程或來源權限。',
    lastSyncedAt: '2026-07-04T18:45:00+08:00',
    updatedAt: '2026-07-04T18:30:00+08:00',
    updatedBy: '許家維',
  },
  {
    id: 'doc-008',
    name: '社會救助申請清單',
    knowledgeBase: '社會福利知識庫',
    source: 'SharePoint / 社會處',
    category: '申請文件',
    version: 'v2.7',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    syncStatus: 'completed',
    readStatus: 'completed',
    searchableStatus: 'completed',
    failureReason: null,
    lastSyncedAt: '2026-06-30T12:02:00+08:00',
    updatedAt: '2026-06-30T11:45:00+08:00',
    updatedBy: '李承翰',
  },
])

export const auditEvents: readonly AuditEvent[] = deepFreeze([
  {
    id: 'audit-010',
    timestamp: '2026-07-07T10:42:18+08:00',
    actor: '系統',
    ip: '192.0.2.210',
    module: '系統管理',
    operationType: 'system',
    action: 'Token 用量異常',
    result: 'failed',
    resource: 'xiaoming.wang@citygpt.example',
    traceId: 'trc-20260707-0010',
    before: {
      monthlyTokenUsage: 282400,
      monthlyTokenThreshold: 300000,
    },
    after: {
      monthlyTokenUsage: 382400,
      monthlyTokenThreshold: 300000,
      overThresholdTokens: 82400,
      alertRule: '單一使用者本月 Token 用量超過一般同仁合理月用量',
      normalUsageBaseline: {
        shortQuestion: { tokens: 800, dailyLimit: 28 },
        documentSummary: { tokens: 2200, dailyLimit: 10 },
        longDocumentAnalysis: { tokens: 5000, dailyLimit: '4-5' },
        recommendedDailyInteractions: '12-18',
        estimatedMonthlyThreshold: 300000,
      },
      emailNotification: {
        status: 'sent',
        recipients: ['IT', 'admin'],
        subject: 'CityGPT Token 用量異常通知',
      },
    },
    permissionDecision: { decision: 'allowed', permission: 'system.audit' },
  },
  {
    id: 'audit-002',
    timestamp: '2026-07-06T08:51:40+08:00',
    actor: '黃品蓁',
    ip: '192.0.2.24',
    module: '使用者與權限',
    operationType: 'management',
    action: '管理者角色異動失敗',
    result: 'failed',
    resource: 'user-005',
    traceId: 'trc-20260706-0002',
    before: { role: 'user', status: 'sso_disabled' },
    after: { role: 'user', status: 'sso_disabled', changed: false },
    permissionDecision: { decision: 'allowed', permission: 'users.manage' },
  },
  {
    id: 'audit-003',
    timestamp: '2026-07-06T08:02:15+08:00',
    actor: '系統',
    ip: '198.51.100.14',
    module: '登入安全',
    operationType: 'login',
    action: 'SSO 登入驗證失敗',
    result: 'failed',
    resource: 'xiaoming.wang@citygpt.example',
    traceId: 'trc-20260706-0003',
    before: null,
    after: {
      provider: '縣府 SSO',
      ssoResult: 'access_denied',
      reason: 'SSO 未核發登入憑證',
    },
    permissionDecision: {
      decision: 'denied',
      permission: 'system.audit',
      reason: 'SSO 回傳 access_denied，CityGPT 未建立登入工作階段',
    },
  },
  {
    id: 'audit-004',
    timestamp: '2026-07-05T17:14:33+08:00',
    actor: '黃品蓁',
    ip: '198.51.100.27',
    module: '稽核日誌',
    operationType: 'download',
    action: '稽核日誌匯出失敗',
    result: 'failed',
    resource: 'audit-export-180d',
    traceId: 'trc-20260705-0004',
    before: null,
    after: {
      format: 'csv',
      rangeDays: 180,
      errorCode: 'EXPORT_TIMEOUT',
      reason: '資料量過大，匯出逾時',
    },
    permissionDecision: { decision: 'allowed', permission: 'audit.view' },
  },
  {
    id: 'audit-007',
    timestamp: '2026-07-04T18:42:21+08:00',
    actor: '李承翰',
    ip: '192.0.2.45',
    module: '使用者與權限',
    operationType: 'login',
    action: 'SSO 停用帳號嘗試登入',
    result: 'failed',
    resource: 'user-005',
    traceId: 'trc-20260704-0007',
    before: { status: 'sso_disabled', source: 'SSO' },
    after: { status: 'sso_disabled', blockedBy: 'SSO' },
    permissionDecision: {
      decision: 'denied',
      permission: 'system.audit',
      reason: 'SSO 回傳帳號已停用',
    },
  },
  {
    id: 'audit-008',
    timestamp: '2026-07-04T15:09:57+08:00',
    actor: '系統',
    ip: '192.0.2.200',
    module: '系統管理',
    operationType: 'query',
    action: '系統判斷敏感或異常',
    result: 'failed',
    resource: 'conversation-009',
    traceId: 'trc-20260704-0008',
    before: { riskScore: 72 },
    after: {
      riskScore: 91,
      reason: '輸入疑似包含帳號密碼或 Token',
      blocked: true,
    },
    permissionDecision: { decision: 'allowed', permission: 'system.audit' },
  },
  {
    id: 'audit-009',
    timestamp: '2026-07-04T13:18:10+08:00',
    actor: '王小明',
    ip: '192.0.2.24',
    module: '權限拒絕',
    operationType: 'login',
    action: '一般USER 嘗試進入後台',
    result: 'failed',
    resource: '/admin',
    traceId: 'trc-20260704-0009',
    before: { role: 'user' },
    after: { blocked: true },
    permissionDecision: {
      decision: 'denied',
      permission: 'users.manage',
      reason: '一般USER 不具備後台管理權限',
    },
  },
])

export const usageStats: readonly UsageStats[] = deepFreeze([
  {
    rangeDays: 7,
    kpis: {
      totalQueries: 12480,
      aiTokens: 18426000,
      activeUsers: 1842,
      averageResponseMs: 1280,
      satisfactionRate: 0.91,
    },
    trends: [
      { date: '2026-07-04', queries: 1710, activeUsers: 298 },
      { date: '2026-07-05', queries: 1665, activeUsers: 276 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 4150, satisfactionRate: 0.93 },
      { name: '社會福利知識庫', queries: 2880, satisfactionRate: 0.9 },
      { name: '民政服務知識庫', queries: 2140, satisfactionRate: 0.89 },
    ],
    featureUsage: [
      { name: '日常問答 / 潤飾', count: 5620 },
      { name: '文件摘要', count: 3840 },
      { name: '法規研析', count: 1490 },
    ],
    departmentUsage: [
      { department: '民政處', queries: 2860, tokens: 4120000 },
      { department: '社會處', queries: 2440, tokens: 3860000 },
      { department: '1999 服務中心', queries: 3180, tokens: 2980000 },
    ],
    roleUsage: [
      { role: 'user', queries: 10890, tokens: 15120000 },
      { role: 'admin', queries: 1590, tokens: 3306000 },
    ],
    citedDocuments: [
      { name: '1999 話術與轉介原則', citations: 1260 },
      { name: '社福津貼資格判斷', citations: 1040 },
      { name: '稽核紀錄保存規範', citations: 680 },
    ],
    qualityIssues: [
      { type: '找不到答案', question: '租屋補貼和急難救助能否同時申請？', count: 46 },
      { type: '搜尋相關度偏低', question: '道路施工案件進度查詢需要哪些資料？', count: 32 },
    ],
    negativeFeedback: {
      count: 438,
      unresolved: 126,
      rate: 0.09,
      commonReasons: [
        { reason: '答非所問', count: 176, description: '回答方向與使用者問題不一致' },
        { reason: '資料不足', count: 142, description: '缺少可引用資料或回答不完整' },
        { reason: '資料過期', count: 72, description: '使用者指出內容不是最新版本' },
      ],
    },
  },
  {
    rangeDays: 30,
    kpis: {
      totalQueries: 51860,
      aiTokens: 75890000,
      activeUsers: 5340,
      averageResponseMs: 1345,
      satisfactionRate: 0.9,
    },
    trends: [
      { date: '2026-06-07', queries: 1490, activeUsers: 268 },
      { date: '2026-06-21', queries: 1760, activeUsers: 301 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 16820, satisfactionRate: 0.92 },
      { name: '社會福利知識庫', queries: 12310, satisfactionRate: 0.9 },
      { name: '建設處知識庫', queries: 8270, satisfactionRate: 0.88 },
    ],
    featureUsage: [
      { name: '日常問答 / 潤飾', count: 23840 },
      { name: '文件摘要', count: 14220 },
      { name: '法規研析', count: 6420 },
    ],
    departmentUsage: [
      { department: '民政處', queries: 11480, tokens: 16820000 },
      { department: '社會處', queries: 10360, tokens: 15100000 },
      { department: '1999 服務中心', queries: 13210, tokens: 12330000 },
    ],
    roleUsage: [
      { role: 'user', queries: 45110, tokens: 62240000 },
      { role: 'admin', queries: 6750, tokens: 13650000 },
    ],
    citedDocuments: [
      { name: '1999 話術與轉介原則', citations: 4420 },
      { name: '社福津貼資格判斷', citations: 3860 },
      { name: '民政戶籍補助說明', citations: 2210 },
    ],
    qualityIssues: [
      { type: '找不到答案', question: '新制長照交通接送補助是否適用跨縣市？', count: 148 },
      { type: '搜尋相關度偏低', question: '建築執照補件期限如何計算？', count: 96 },
    ],
    negativeFeedback: {
      count: 1842,
      unresolved: 384,
      rate: 0.1,
      commonReasons: [
        { reason: '答非所問', count: 720, description: '回答方向與使用者問題不一致' },
        { reason: '資料不足', count: 618, description: '缺少可引用資料或回答不完整' },
        { reason: '引用錯誤', count: 206, description: '使用者指出引用來源不符合問題' },
      ],
    },
  },
  {
    rangeDays: 90,
    kpis: {
      totalQueries: 142730,
      aiTokens: 208430000,
      activeUsers: 9815,
      averageResponseMs: 1410,
      satisfactionRate: 0.885,
    },
    trends: [
      { date: '2026-04-08', queries: 1280, activeUsers: 231 },
      { date: '2026-05-23', queries: 1585, activeUsers: 279 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 45110, satisfactionRate: 0.91 },
      { name: '社會福利知識庫', queries: 32180, satisfactionRate: 0.89 },
      { name: '民政服務知識庫', queries: 22420, satisfactionRate: 0.87 },
    ],
    featureUsage: [
      { name: '日常問答 / 潤飾', count: 65320 },
      { name: '文件摘要', count: 39440 },
      { name: '法規研析', count: 18280 },
    ],
    departmentUsage: [
      { department: '民政處', queries: 31840, tokens: 46320000 },
      { department: '社會處', queries: 28610, tokens: 42110000 },
      { department: '1999 服務中心', queries: 36200, tokens: 33840000 },
    ],
    roleUsage: [
      { role: 'user', queries: 124860, tokens: 171200000 },
      { role: 'admin', queries: 17870, tokens: 37230000 },
    ],
    citedDocuments: [
      { name: '1999 話術與轉介原則', citations: 12240 },
      { name: '社福津貼資格判斷', citations: 10680 },
      { name: '社會救助申請清單', citations: 8420 },
    ],
    qualityIssues: [
      { type: '找不到答案', question: '弱勢家庭多項補助的排除條件有哪些？', count: 386 },
      { type: '搜尋相關度偏低', question: '工務通報與1999案件如何合併查詢？', count: 244 },
    ],
    negativeFeedback: {
      count: 5260,
      unresolved: 920,
      rate: 0.115,
      commonReasons: [
        { reason: '資料不足', count: 1860, description: '缺少可引用資料或回答不完整' },
        { reason: '答非所問', count: 1715, description: '回答方向與使用者問題不一致' },
        { reason: '資料過期', count: 820, description: '使用者指出內容不是最新版本' },
      ],
    },
  },
])

export const userTrafficStats: readonly UserTrafficStats[] = deepFreeze([
  {
    id: 'traffic-001',
    name: '王小明',
    email: 'xiaoming.wang@citygpt.example',
    role: 'user',
    department: '民政處',
    monthlyTokens: 382400,
    monthlyQueries: 164,
    dailyAverageQueries: 16.4,
    tokenLimit: 300000,
    alertLevel: 'alert',
    lastActivityAt: '2026-07-07T10:42:18+08:00',
    note: '已超過月門檻，建立稽核事件並通知 IT / admin。',
  },
  {
    id: 'traffic-002',
    name: '林佳蓉',
    email: 'jiarong.lin@citygpt.example',
    role: 'user',
    department: '社會處',
    monthlyTokens: 268900,
    monthlyQueries: 132,
    dailyAverageQueries: 13.2,
    tokenLimit: 300000,
    alertLevel: 'watch',
    lastActivityAt: '2026-07-07T09:30:00+08:00',
    note: '已達 80% 觀察線，統計頁提示但不寫入稽核日誌。',
  },
  {
    id: 'traffic-003',
    name: '陳怡君',
    email: 'yijun.chen@citygpt.example',
    role: 'admin',
    department: '資訊處',
    monthlyTokens: 218600,
    monthlyQueries: 118,
    dailyAverageQueries: 11.8,
    tokenLimit: 300000,
    alertLevel: 'normal',
    lastActivityAt: '2026-07-07T08:12:00+08:00',
    note: '正常使用，僅保留於流量統計。',
  },
  {
    id: 'traffic-004',
    name: '張志豪',
    email: 'zhihao.chang@citygpt.example',
    role: 'user',
    department: '1999 服務中心',
    monthlyTokens: 146200,
    monthlyQueries: 74,
    dailyAverageQueries: 7.4,
    tokenLimit: 300000,
    alertLevel: 'normal',
    lastActivityAt: '2026-07-06T16:45:00+08:00',
    note: '正常使用，適合用於部門 KPI 與成本估算。',
  },
])

export const feedbackItems: readonly FeedbackItem[] = deepFreeze([
  {
    id: 'feedback-001',
    sentiment: 'negative',
    rating: 3,
    question: '請問民政戶籍補助可以同時申請哪些項目？',
    answer: '系統只回答了其中一種補助，沒有說明合併申請限制。',
    knowledgeBase: '民政服務知識庫',
    tags: ['補助', '答案不完整'],
    status: 'pending',
    createdAt: '2026-07-06T08:28:00+08:00',
    assignee: null,
    note: '需要補上 2026 年最新補助合併規則。',
    citations: [
      {
        documentId: 'doc-001',
        documentName: '民政戶籍補助說明',
        excerpt: '民政補助需依申請人身分與年度公告判斷。',
      },
    ],
    context: {
      traceId: 'feedback-trc-001',
      conversationId: 'conversation-001',
      channel: 'CityGPT 入口網站',
    },
  },
  {
    id: 'feedback-002',
    sentiment: 'positive',
    rating: 9,
    question: '社福津貼資格判斷要準備哪些文件？',
    answer: '系統列出身分證明、收入證明與申請書，並附上來源。',
    knowledgeBase: '社會福利知識庫',
    tags: ['津貼資格', '文件清單'],
    status: 'completed',
    createdAt: '2026-07-05T19:45:00+08:00',
    assignee: '社福知識維護小組',
    note: '使用者確認資訊完整。',
    citations: [
      {
        documentId: 'doc-003',
        documentName: '社福津貼資格判斷',
        excerpt: '申請人須檢附身分、收入與戶籍相關文件。',
      },
    ],
    context: {
      traceId: 'feedback-trc-002',
      conversationId: 'conversation-002',
      channel: 'LINE 官方帳號',
    },
  },
  {
    id: 'feedback-003',
    sentiment: 'negative',
    rating: 4,
    question: '1999 轉接到承辦窗口時要提供哪些資料？',
    answer: '答案只有說明「請留下資料」，但沒有列出欄位。',
    knowledgeBase: '市政服務知識庫',
    tags: ['客服話術', '缺少欄位'],
    status: 'in_progress',
    createdAt: '2026-07-05T14:12:00+08:00',
    assignee: '客服知識維護小組',
    note: '正在補齊姓名、電話、案件主旨與回覆期限。',
    citations: [
      {
        documentId: 'doc-006',
        documentName: '1999 話術與轉介原則',
        excerpt: '轉介案件需留下可供承辦單位聯繫的基本資料。',
      },
    ],
    context: {
      traceId: 'feedback-trc-003',
      conversationId: 'conversation-003',
      channel: 'CityGPT 入口網站',
    },
  },
  {
    id: 'feedback-004',
    sentiment: 'positive',
    rating: 8,
    question: '建築執照審查通常需要幾個工作天？',
    answer: '依案件類型列出 7 至 21 個工作天，並提醒以實際審查為準。',
    knowledgeBase: '建設處知識庫',
    tags: ['建築管理', '審查天數'],
    status: 'completed',
    createdAt: '2026-07-04T16:22:00+08:00',
    assignee: '建設處知識維護小組',
    note: '已確認引用文件版本正確。',
    citations: [
      {
        documentId: 'doc-004',
        documentName: '建築執照流程說明',
        excerpt: '審查天數會依案件規模、補件次數與法定流程不同。',
      },
    ],
    context: {
      traceId: 'feedback-trc-004',
      conversationId: 'conversation-004',
      channel: '客服後臺',
    },
  },
  {
    id: 'feedback-005',
    sentiment: 'negative',
    rating: 2,
    question: '道路施工案件查詢不到目前進度，該怎麼處理？',
    answer: '請洽承辦單位確認進度。',
    knowledgeBase: '工務處知識庫',
    tags: ['工程進度', '答案太籠統'],
    status: 'ignored',
    createdAt: '2026-07-03T20:06:00+08:00',
    assignee: '工務知識維護小組',
    note: '測試資料不列入 KPI。',
    citations: [
      {
        documentId: 'doc-007',
        documentName: '工務案件進度查詢',
        excerpt: '工程案件進度會依公開資料介接時間更新。',
      },
    ],
    context: {
      traceId: 'feedback-trc-005',
      conversationId: 'conversation-005',
      channel: 'LINE 官方帳號',
    },
  },
  {
    id: 'feedback-006',
    sentiment: 'positive',
    rating: 7,
    question: '社會救助申請清單有分成人與兒少嗎？',
    answer: '有，系統已依申請類型列出不同附件清單。',
    knowledgeBase: '社會福利知識庫',
    tags: ['申請文件', '分類清楚'],
    status: 'in_progress',
    createdAt: '2026-07-02T11:38:00+08:00',
    assignee: '社福知識維護小組',
    note: '等待處室確認新表單連結。',
    citations: [
      {
        documentId: 'doc-008',
        documentName: '社會救助申請清單',
        excerpt: '不同對象需檢附不同附件，請依申請類型選擇。',
      },
    ],
    context: {
      traceId: 'feedback-trc-006',
      conversationId: 'conversation-006',
      channel: 'CityGPT 入口網站',
    },
  },
])
