import type {
  AdminUser,
  AuditEvent,
  FeedbackItem,
  KnowledgeDocument,
  UsageStats,
} from './types'

const deepFreeze = <T>(value: T): Readonly<T> => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value)
    for (const nested of Object.values(value as Record<string, unknown>)) {
      deepFreeze(nested)
    }
  }

  return value as Readonly<T>
}

export const adminUsers: readonly AdminUser[] = deepFreeze([
  {
    id: 'user-001',
    name: '王小明',
    email: 'xiaoming.wang@citygpt.example',
    department: '民政處',
    role: 'user',
    status: 'active',
    lastLogin: '2026-07-06T08:42:00+08:00',
  },
  {
    id: 'user-002',
    name: '林怡君',
    email: 'yijun.lin@citygpt.example',
    department: '資訊管理處',
    role: 'user',
    status: 'active',
    lastLogin: '2026-07-06T09:05:00+08:00',
  },
  {
    id: 'user-003',
    name: '陳志豪',
    email: 'zhihao.chen@citygpt.example',
    department: '政風處',
    role: 'user',
    status: 'active',
    lastLogin: '2026-07-05T16:18:00+08:00',
  },
  {
    id: 'user-004',
    name: '張雅雯',
    email: 'yawen.zhang@citygpt.example',
    department: '教育處',
    role: 'user',
    status: 'invited',
    lastLogin: null,
  },
  {
    id: 'user-005',
    name: '李承翰',
    email: 'chenghan.li@citygpt.example',
    department: '社會處',
    role: 'admin',
    status: 'suspended',
    lastLogin: '2026-06-19T11:27:00+08:00',
  },
  {
    id: 'user-006',
    name: '黃品蓁',
    email: 'pinzhen.huang@citygpt.example',
    department: '建設處',
    role: 'admin',
    status: 'active',
    lastLogin: '2026-07-04T14:03:00+08:00',
  },
  {
    id: 'user-007',
    name: '許家維',
    email: 'jiawei.xu@citygpt.example',
    department: '工務處',
    role: 'admin',
    status: 'invited',
    lastLogin: null,
  },
])

export const knowledgeDocuments: readonly KnowledgeDocument[] = deepFreeze([
  {
    id: 'doc-001',
    name: '民政戶籍補助說明',
    knowledgeBase: '民政服務知識庫',
    category: '補助與申請',
    version: 'v2.1-draft',
    access: 'department',
    published: false,
    indexStatus: 'pending',
    updatedAt: '2026-07-05T13:20:00+08:00',
    updatedBy: '王小明',
  },
  {
    id: 'doc-002',
    name: '1999 服務 FAQ',
    knowledgeBase: '市政服務知識庫',
    category: '常見問題',
    version: 'v4.3',
    access: 'public',
    published: true,
    indexStatus: 'failed',
    updatedAt: '2026-07-06T07:35:00+08:00',
    updatedBy: '林怡君',
  },
  {
    id: 'doc-003',
    name: '社福津貼資格判斷',
    knowledgeBase: '社會福利知識庫',
    category: '福利資格',
    version: 'v3.0',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-07-03T10:05:00+08:00',
    updatedBy: '李承翰',
  },
  {
    id: 'doc-004',
    name: '建築執照流程說明',
    knowledgeBase: '建設處知識庫',
    category: '建築管理',
    version: 'v1.8',
    access: 'department',
    published: true,
    indexStatus: 'indexing',
    updatedAt: '2026-07-05T17:10:00+08:00',
    updatedBy: '黃品蓁',
  },
  {
    id: 'doc-005',
    name: '稽核紀錄保存規範',
    knowledgeBase: '資安稽核知識庫',
    category: '稽核',
    version: 'v2.4',
    access: 'restricted',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-06-28T15:42:00+08:00',
    updatedBy: '陳志豪',
  },
  {
    id: 'doc-006',
    name: '1999 話術與轉介原則',
    knowledgeBase: '市政服務知識庫',
    category: '客服話術',
    version: 'v5.2',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-07-01T09:12:00+08:00',
    updatedBy: '張雅雯',
  },
  {
    id: 'doc-007',
    name: '工務案件進度查詢',
    knowledgeBase: '工務處知識庫',
    category: '道路與工程',
    version: 'v1.6',
    access: 'restricted',
    published: false,
    indexStatus: 'pending',
    updatedAt: '2026-07-04T18:30:00+08:00',
    updatedBy: '許家維',
  },
  {
    id: 'doc-008',
    name: '社會救助申請清單',
    knowledgeBase: '社會福利知識庫',
    category: '申請文件',
    version: 'v2.7',
    access: 'public',
    published: true,
    indexStatus: 'completed',
    updatedAt: '2026-06-30T11:45:00+08:00',
    updatedBy: '李承翰',
  },
])

export const auditEvents: readonly AuditEvent[] = deepFreeze([
  {
    id: 'audit-001',
    timestamp: '2026-07-06T09:08:12+08:00',
    actor: '林怡君',
    ip: '192.0.2.10',
    module: '使用者與權限',
    action: '新增使用者',
    result: 'success',
    resource: 'user-007',
    traceId: 'trc-20260706-0001',
    before: null,
    after: { role: 'admin', status: 'invited' },
    permissionDecision: { decision: 'allowed', permission: 'users.manage' },
  },
  {
    id: 'audit-002',
    timestamp: '2026-07-06T08:51:40+08:00',
    actor: '王小明',
    ip: '192.0.2.24',
    module: '文件與知識庫',
    action: '更新文件版本',
    result: 'success',
    resource: 'doc-001',
    traceId: 'trc-20260706-0002',
    before: { version: 'v2.0-draft' },
    after: { version: 'v2.1-draft' },
    permissionDecision: { decision: 'allowed', permission: 'knowledge.manage' },
  },
  {
    id: 'audit-003',
    timestamp: '2026-07-06T08:02:15+08:00',
    actor: '張雅雯',
    ip: '198.51.100.14',
    module: '文件與知識庫',
    action: '下架文件',
    result: 'failed',
    resource: 'doc-006',
    traceId: 'trc-20260706-0003',
    before: { published: true },
    after: { published: true },
    permissionDecision: {
      decision: 'denied',
      permission: 'knowledge.manage',
      reason: '分析人員不可管理文件生命週期',
    },
  },
  {
    id: 'audit-004',
    timestamp: '2026-07-05T17:14:33+08:00',
    actor: '黃品蓁',
    ip: '198.51.100.27',
    module: '使用統計',
    action: '匯出 30 天統計',
    result: 'success',
    resource: 'stats-30d-education',
    traceId: 'trc-20260705-0004',
    before: null,
    after: { format: 'csv', rangeDays: 30 },
    permissionDecision: { decision: 'allowed', permission: 'stats.view' },
  },
  {
    id: 'audit-005',
    timestamp: '2026-07-05T16:22:08+08:00',
    actor: '陳志豪',
    ip: '203.0.113.8',
    module: '稽核日誌',
    action: '查看失敗事件',
    result: 'success',
    resource: 'audit-filter-failed',
    traceId: 'trc-20260705-0005',
    before: { filter: 'all' },
    after: { filter: 'failed' },
    permissionDecision: { decision: 'allowed', permission: 'audit.view' },
  },
  {
    id: 'audit-006',
    timestamp: '2026-07-05T14:36:49+08:00',
    actor: '李承翰',
    ip: '203.0.113.31',
    module: '回饋管理',
    action: '指派負責人',
    result: 'failed',
    resource: 'feedback-004',
    traceId: 'trc-20260705-0006',
    before: { assignee: null },
    after: { assignee: null },
    permissionDecision: {
      decision: 'denied',
      permission: 'feedback.manage',
      reason: '帳號已停用',
    },
  },
  {
    id: 'audit-007',
    timestamp: '2026-07-04T18:42:21+08:00',
    actor: '許家維',
    ip: '192.0.2.45',
    module: '使用者與權限',
    action: '啟用帳號',
    result: 'failed',
    resource: 'user-005',
    traceId: 'trc-20260704-0007',
    before: { status: 'suspended' },
    after: { status: 'suspended' },
    permissionDecision: {
      decision: 'denied',
      permission: 'users.manage',
      reason: '邀請尚未完成驗證',
    },
  },
  {
    id: 'audit-008',
    timestamp: '2026-07-04T15:09:57+08:00',
    actor: '索引服務',
    ip: '192.0.2.200',
    module: '文件與知識庫',
    action: '重新建立索引',
    result: 'failed',
    resource: 'doc-002',
    traceId: 'trc-20260704-0008',
    before: { indexStatus: 'indexing' },
    after: {
      indexStatus: 'failed',
      error: { code: 'CONTENT_PARSE_ERROR', retryable: false },
    },
    permissionDecision: { decision: 'allowed', permission: 'knowledge.manage' },
  },
])

export const usageStats: readonly UsageStats[] = deepFreeze([
  {
    rangeDays: 7,
    kpis: {
      totalQueries: 12480,
      activeUsers: 1842,
      averageResponseMs: 1280,
      satisfactionRate: 0.91,
    },
    trends: [
      { date: '2026-07-04', queries: 1710, activeUsers: 298 },
      { date: '2026-07-05', queries: 1665, activeUsers: 276 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 4150, satisfactionRate: 0.93 },
      { name: '社會福利知識庫', queries: 2880, satisfactionRate: 0.9 },
      { name: '民政服務知識庫', queries: 2140, satisfactionRate: 0.89 },
    ],
    departmentRanking: [
      { department: '教育處', queries: 2380, activeUsers: 310 },
      { department: '社會處', queries: 2015, activeUsers: 274 },
      { department: '民政處', queries: 1840, activeUsers: 236 },
    ],
    unansweredRate: 0.043,
    errorSummaries: [
      { code: 'NO_MATCH', count: 312, description: '找不到可引用的知識來源' },
      { code: 'INDEX_UNAVAILABLE', count: 47, description: '索引尚未完成或暫時不可用' },
    ],
  },
  {
    rangeDays: 30,
    kpis: {
      totalQueries: 51860,
      activeUsers: 5340,
      averageResponseMs: 1345,
      satisfactionRate: 0.9,
    },
    trends: [
      { date: '2026-06-07', queries: 1490, activeUsers: 268 },
      { date: '2026-06-21', queries: 1760, activeUsers: 301 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 16820, satisfactionRate: 0.92 },
      { name: '社會福利知識庫', queries: 12310, satisfactionRate: 0.9 },
      { name: '建設處知識庫', queries: 8270, satisfactionRate: 0.88 },
    ],
    departmentRanking: [
      { department: '教育處', queries: 9840, activeUsers: 872 },
      { department: '社會處', queries: 8650, activeUsers: 741 },
      { department: '建設處', queries: 7290, activeUsers: 688 },
    ],
    unansweredRate: 0.049,
    errorSummaries: [
      { code: 'NO_MATCH', count: 1422, description: '找不到可引用的知識來源' },
      { code: 'TIMEOUT', count: 118, description: '回覆時間超過服務門檻' },
    ],
  },
  {
    rangeDays: 90,
    kpis: {
      totalQueries: 142730,
      activeUsers: 9815,
      averageResponseMs: 1410,
      satisfactionRate: 0.885,
    },
    trends: [
      { date: '2026-04-08', queries: 1280, activeUsers: 231 },
      { date: '2026-05-23', queries: 1585, activeUsers: 279 },
      { date: '2026-07-06', queries: 2014, activeUsers: 332 },
    ],
    popularKnowledgeBases: [
      { name: '市政服務知識庫', queries: 45110, satisfactionRate: 0.91 },
      { name: '社會福利知識庫', queries: 32180, satisfactionRate: 0.89 },
      { name: '民政服務知識庫', queries: 22420, satisfactionRate: 0.87 },
    ],
    departmentRanking: [
      { department: '教育處', queries: 26340, activeUsers: 1570 },
      { department: '社會處', queries: 23870, activeUsers: 1432 },
      { department: '民政處', queries: 19740, activeUsers: 1215 },
    ],
    unansweredRate: 0.054,
    errorSummaries: [
      { code: 'NO_MATCH', count: 4280, description: '找不到可引用的知識來源' },
      { code: 'SOURCE_STALE', count: 306, description: '引用文件可能不是最新版本' },
    ],
  },
])

export const feedbackItems: readonly FeedbackItem[] = deepFreeze([
  {
    id: 'feedback-001',
    sentiment: 'negative',
    question: '請問民政戶籍補助可以同時申請哪些項目？',
    answer: '系統只回答了其中一種補助，沒有說明合併申請限制。',
    department: '民政處',
    knowledgeBase: '民政服務知識庫',
    tags: ['補助', '答案不完整'],
    status: 'pending',
    createdAt: '2026-07-06T08:28:00+08:00',
    assignee: null,
    note: '需要補上 2026 年最新補助合併規則。',
    citations: [
      {
        documentId: 'doc-001',
        documentName: '民政戶籍補助說明',
        excerpt: '民政補助需依申請人身分與年度公告判斷。',
      },
    ],
    context: {
      traceId: 'feedback-trc-001',
      conversationId: 'conversation-001',
      channel: 'CityGPT 入口網站',
    },
  },
  {
    id: 'feedback-002',
    sentiment: 'positive',
    question: '社福津貼資格判斷要準備哪些文件？',
    answer: '系統列出身分證明、收入證明與申請書，並附上來源。',
    department: '社會處',
    knowledgeBase: '社會福利知識庫',
    tags: ['津貼資格', '文件清單'],
    status: 'completed',
    createdAt: '2026-07-05T19:45:00+08:00',
    assignee: '社福知識維護小組',
    note: '使用者確認資訊完整。',
    citations: [
      {
        documentId: 'doc-003',
        documentName: '社福津貼資格判斷',
        excerpt: '申請人須檢附身分、收入與戶籍相關文件。',
      },
    ],
    context: {
      traceId: 'feedback-trc-002',
      conversationId: 'conversation-002',
      channel: 'LINE 官方帳號',
    },
  },
  {
    id: 'feedback-003',
    sentiment: 'negative',
    question: '1999 轉接到承辦窗口時要提供哪些資料？',
    answer: '答案只有說明「請留下資料」，但沒有列出欄位。',
    department: '教育處',
    knowledgeBase: '市政服務知識庫',
    tags: ['客服話術', '缺少欄位'],
    status: 'in_progress',
    createdAt: '2026-07-05T14:12:00+08:00',
    assignee: '客服知識維護小組',
    note: '正在補齊姓名、電話、案件主旨與回覆期限。',
    citations: [
      {
        documentId: 'doc-006',
        documentName: '1999 話術與轉介原則',
        excerpt: '轉介案件需留下可供承辦單位聯繫的基本資料。',
      },
    ],
    context: {
      traceId: 'feedback-trc-003',
      conversationId: 'conversation-003',
      channel: 'CityGPT 入口網站',
    },
  },
  {
    id: 'feedback-004',
    sentiment: 'positive',
    question: '建築執照審查通常需要幾個工作天？',
    answer: '依案件類型列出 7 至 21 個工作天，並提醒以實際審查為準。',
    department: '建設處',
    knowledgeBase: '建設處知識庫',
    tags: ['建築管理', '審查天數'],
    status: 'completed',
    createdAt: '2026-07-04T16:22:00+08:00',
    assignee: '建設處知識維護小組',
    note: '已確認引用文件版本正確。',
    citations: [
      {
        documentId: 'doc-004',
        documentName: '建築執照流程說明',
        excerpt: '審查天數會依案件規模、補件次數與法定流程不同。',
      },
    ],
    context: {
      traceId: 'feedback-trc-004',
      conversationId: 'conversation-004',
      channel: '客服後臺',
    },
  },
  {
    id: 'feedback-005',
    sentiment: 'negative',
    question: '道路施工案件查詢不到目前進度，該怎麼處理？',
    answer: '請洽承辦單位確認進度。',
    department: '資訊管理處',
    knowledgeBase: '工務處知識庫',
    tags: ['工程進度', '答案太籠統'],
    status: 'ignored',
    createdAt: '2026-07-03T20:06:00+08:00',
    assignee: '工務知識維護小組',
    note: '測試資料不列入 KPI。',
    citations: [
      {
        documentId: 'doc-007',
        documentName: '工務案件進度查詢',
        excerpt: '工程案件進度會依公開資料介接時間更新。',
      },
    ],
    context: {
      traceId: 'feedback-trc-005',
      conversationId: 'conversation-005',
      channel: 'LINE 官方帳號',
    },
  },
  {
    id: 'feedback-006',
    sentiment: 'positive',
    question: '社會救助申請清單有分成人與兒少嗎？',
    answer: '有，系統已依申請類型列出不同附件清單。',
    department: '社會處',
    knowledgeBase: '社會福利知識庫',
    tags: ['申請文件', '分類清楚'],
    status: 'in_progress',
    createdAt: '2026-07-02T11:38:00+08:00',
    assignee: '社福知識維護小組',
    note: '等待處室確認新表單連結。',
    citations: [
      {
        documentId: 'doc-008',
        documentName: '社會救助申請清單',
        excerpt: '不同對象需檢附不同附件，請依申請類型選擇。',
      },
    ],
    context: {
      traceId: 'feedback-trc-006',
      conversationId: 'conversation-006',
      channel: 'CityGPT 入口網站',
    },
  },
])
